baseURL = 'https://ian.limarta.org/'
languageCode = 'en-us'
theme = 'hugo-bearblog'
author = "Ian Limarta"
title = "Ian Limarta"

sectionPagesMenu = 'main'

#[permalinks]
#  blog = "/:slug/"
#  tags = "/blog/:slug"

# enableRobotsTXT = true

[params]
  description = "what?"
  favicon = "images/favicon.png"
  mathjax = false

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  images = ["images/share.png"]


[caches]
  [caches.images]
    dir = ':cacheDir/images'